config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :items
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new 
  end

  def index
    @items = Item.all
    @a = 0
    Item.all.each do |item|
      @a += item.cost.to_i
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item].permit(:title, :cost))
    @item.save
    redirect_to @item
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.erb
<h1> All items </h1>
<table>
  <tr>
    <th>Title</th>
    <th>Cost</th>
    <th></th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.cost %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
    </tr>
  <% end %>
</table>
<strong>Total cost = </strong>
<%= @a %>

app/views/items/new.html.erb
<h1> Adding a new item </h1>
<%= form_with scope: :item, url: items_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :cost %><br>
    <%= form.number_field :cost %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Expense tracker </h1>